#!/bin/sh

echo " $(spt playback)"

# class=$(playerctl metadata --player=spotify --format '{{lc(status)}}')
# icon=""
# spt playback

# if [[ $class == "playing" ]]; then
#   info=$(playerctl metadata --player=spotify --format '{{artist}} - {{title}}')
#   if [[ ${#info} > 40 ]]; then
#     info=$(echo $info | cut -c1-40)"..."
#   fi
#   text=$info" "$icon
# elif [[ $class == "paused" ]]; then
#   text=$icon
# elif [[ $class == "stopped" ]]; then
#   text=""
# fi

# text=$info" "$icon
# echo -e "{\"text\":\""$text"\", \"class\":\""$class"\"}"
